#!/bin/bash
set -e

root=$(dirname $0)
cd "$root"

unset LD_PRELOAD

iar="/opt/IAR2/common/bin/iarbuild.exe"
err="Break with errors"
no_compile=0
no_generate_vkp=0
args=$@

for i in ${args}; do
  if [ $i == "--no_compile" ]; then
    no_compile=1
  elif [ $i == "--no_gen_vkp" ]; then
    no_generate_vkp=1
  elif [ $i == "--help" ]; then
    echo " Automated script for buld siemens loader v0.1 "
    echo "                  (c) Z.Vova(STANOK) 2011-2012 "
    echo "	Usage:"
    echo "		--no_compile - do not compile elfloader"
    echo "		--no_gen_vkp - do not generate patchs"
    echo ""
    exit 0
  else
    echo "Unknow parameter $i"
  fi
done

TIMESTAMP="$(date +'%d.%m.%Y')"

# Removed: S75sw47 S75sw40 S68sw47
MODELS=(
	"C72sw22" "C75sw22" "C75sw24" "C81sw51" "CX70sw56" "CX75sw13" "CX75sw25" "E71sw45" "EL71sw45" "M75sw25"
	"S65sw58" "S68sw52" "S75sw52" "SK65sw50" "SL65sw53" "SL75sw47" "SL75sw52"
	"CL61sw00_db128" "CF75sw23"
)

# MODELS=("E71sw45" "CX75sw25")

if [ $no_generate_vkp == 0 ]; then
	for model in ${MODELS[*]}; do
		echo "CCLD  $model..."
		wine $iar ElfLoader.ewp -make $model -log warnings
		echo "------------------------------------------------------"
	done
fi

if [ $no_generate_vkp == 0 ]; then
	for model in ${MODELS[*]}; do
		echo "HEX  $model..."
		./postbuild $model $TIMESTAMP
	done
fi
