#!/bin/bash
set -e

root=$(dirname $0)
cd "$root"

unset LD_PRELOAD

model=$1
TIMESTAMP=$2

FF="$root/../ff/$model.bin"
out="$root/$model/Exe"
out_vkp="$root/../release/ElfPack_$model.vkp"
out_vkp_tmp="$root/../release/ElfPack_$model.vkp.tmp"

# Генерируем патч
if [ -f $FF ]; then
	echo 'FullFlash found, generating vkp with recovery info.'
	wine elf2vkp.exe "${out}/ElfLoader.elf" "${out}/ElfLoader3.vkp" "${FF}" &> /dev/null
	FF_EXISTS=1
else
	FF_EXISTS=0
	echo 'FullFlash not found, generating vkp without recovery info!!!'
	wine elf2vkp.exe "${out}/ElfLoader.elf" "${out}/ElfLoader3.vkp" &> /dev/null
fi

echo ";"$model > $out_vkp_tmp
cat "$root/copyright.txt" >> $out_vkp_tmp
echo ";Date: "${TIMESTAMP} >> $out_vkp_tmp
echo -e "\n" >> $out_vkp_tmp
cat "$out/ElfLoader3.vkp" >> $out_vkp_tmp

rm "${out}/ElfLoader3.vkp"

if [[ -f "$out_vkp" ]]; then
	old_md5sum=$(cat "$out_vkp" | grep -v '^;' | grep -v "^$" | md5sum | awk '{print $1}')
	new_md5sum=$(cat "$out_vkp_tmp" | grep -v '^;' | grep -v "^$" | md5sum | awk '{print $1}')
	
	if [[ "$old_md5sum" != "$new_md5sum" ]]; then
		cp -v "$out_vkp_tmp" "$out_vkp"
	fi
else
	cp -v "$out_vkp_tmp" "$out_vkp"
fi

rm "$out_vkp_tmp"

echo "VKP: $out_vkp"
echo ""
