#!/bin/bash
set -e

root=$(dirname $0)
cd "$root"

unset LD_PRELOAD

model=$1
TIMESTAMP=$2

FF="$root/../ff/$model.bin"
out="$root/$model/Exe"
out_vkp="$root/../release/ElfPack_$model.vkp"

# Генерируем патч
if [ -f $FF ]; then
	echo 'FullFlash found, generating vkp with recovery info.'
	wine elf2vkp.exe "${out}/ElfLoader.elf" "${out}/ElfLoader3.vkp" "${FF}" &> /dev/null
	FF_EXISTS=1
else
	FF_EXISTS=0
	echo 'FullFlash not found, generating vkp without recovery info!!!'
	wine elf2vkp.exe "${out}/ElfLoader.elf" "${out}/ElfLoader3.vkp" &> /dev/null
fi

rm -f $out_vkp

# если фул не найден - старые данные == FF
if [ $FF_EXISTS == 0 ]; then
	echo "#pragma enable old_equal_ff" >> $out_vkp
fi
cat "$out/ElfLoader3.vkp" >> $out_vkp
if [ $FF_EXISTS == 0 ]; then
	echo "#pragma disable old_equal_ff" >> $out_vkp
fi

rm "${out}/ElfLoader3.vkp"
# rm "${out}/ElfLoader.elf"

echo "VKP: $out_vkp"
echo ""
