
#include "ep3.asm"


	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)



defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02FCF9C+1  
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02FCD60+1 
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA097A6F2+1
	
	PUBLIC	PITgetN
PITgetN:
	DCD	0xA0A2BC40
	
	PUBLIC	PITret
PITret:
	DCD	0xA0978B92+1

	defadr	StoreErrInfoAndAbort,0xA01CEE50
	defadr	StoreErrString,0xA01CED1C

; <config>
; Autogenerated with tools/porting.js

	defadr	OldFuncInOsInit,0xA02311F4
	defadr	B_SkipSimErrorPopup,0xA029BF06+1
	defadr	B_SocketFuncSocketReadStatus,0xA0A4D866+1
	defadr	B_SocketFuncSocketExitLoop,0xA0A4D888+1
	defadr	B_SocketFuncBindReadStatus,0xA0A4DB82+1
	defadr	B_SocketFuncBindExitLoop,0xA0A4DBA4+1
	defadr	B_SocketFuncConnectReadStatus,0xA0A4DD8A+1
	defadr	B_SocketFuncConnectExitLoop,0xA0A4DDAC+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0A4DF24+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0A4DF46+1
	defadr	B_SocketFuncRecvReadStatus,0xA0A4E14A+1
	defadr	B_SocketFuncRecvExitLoop,0xA0A4E16C+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0A4E1D6+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0A4E1F8+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0A4E94A+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0A4E96C+1
	defadr	B_SocketFuncListenReadStatus,0xA0A4EAC4+1
	defadr	B_SocketFuncListenExitLoop,0xA0A4EAE6+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0A4E390+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0A4E3B2+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0A4E428+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0A4E44A+1
	defadr	B_SocketFuncSendReadStatus,0xA0A4E640+1
	defadr	B_SocketFuncSendExitLoop,0xA0A4E662+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0A4E708+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0A4E72A+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0A4F036+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0A4F058+1
	defadr	NU_Sleep,0xA00A275C

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
