//(p) Hotter

#include "ep3.asm"


	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)



defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE
        

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02D29B2+1
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02D2792+1
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA07FD766+1

	PUBLIC	PITgetN
PITgetN:
	DCD	0xA08A12A4
	
	PUBLIC	PITret
PITret:
	DCD	0xA07FBC06+1

	defadr	StoreErrInfoAndAbort,0xA018DB5C
	defadr	StoreErrString,0xA018DA28

; <config>
; Autogenerated with tools/src/porting.ts

	defadr	OldFuncInOsInit,0xA01F93C0
	defadr	B_SkipSimErrorPopup,0xA02660D0+1
	defadr	B_SocketFuncSocketReadStatus,0xA0B47312+1
	defadr	B_SocketFuncSocketExitLoop,0xA0B47334+1
	defadr	B_SocketFuncBindReadStatus,0xA0B4762E+1
	defadr	B_SocketFuncBindExitLoop,0xA0B47650+1
	defadr	B_SocketFuncConnectReadStatus,0xA0B47836+1
	defadr	B_SocketFuncConnectExitLoop,0xA0B47858+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0B479D0+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0B479F2+1
	defadr	B_SocketFuncRecvReadStatus,0xA0B47BF6+1
	defadr	B_SocketFuncRecvExitLoop,0xA0B47C18+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0B47C82+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0B47CA4+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0B483F6+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0B48418+1
	defadr	B_SocketFuncListenReadStatus,0xA0B48570+1
	defadr	B_SocketFuncListenExitLoop,0xA0B48592+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0B47E3C+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0B47E5E+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0B47ED4+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0B47EF6+1
	defadr	B_SocketFuncSendReadStatus,0xA0B480EC+1
	defadr	B_SocketFuncSendExitLoop,0xA0B4810E+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0B481B4+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0B481D6+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0B48AE2+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0B48B04+1
	defadr	NU_Sleep,0xA00A1FB8

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
