#include "ep3.asm"
#include "ll_init.asm"
	
	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)

defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE
        

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02FF192+1
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02FEF78+1
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA0977CF2+1
	
	PUBLIC	PITgetN
PITgetN:
	DCD	0xA0A280B0
	
	PUBLIC	PITret
PITret:
	DCD	0xA0976192+1

	defadr	StoreErrInfoAndAbort,   0xA01CEE50
	defadr	StoreErrString,         0xA01CED1C

; <config>
; Autogenerated with tools/src/porting.ts

	defadr	OldFuncInOsInit,0xA0231300
	defadr	B_SkipSimErrorPopup,0xA029BEF2+1
	defadr	B_SocketFuncSocketReadStatus,0xA0A49CD6+1
	defadr	B_SocketFuncSocketExitLoop,0xA0A49CF8+1
	defadr	B_SocketFuncBindReadStatus,0xA0A49FF2+1
	defadr	B_SocketFuncBindExitLoop,0xA0A4A014+1
	defadr	B_SocketFuncConnectReadStatus,0xA0A4A1FA+1
	defadr	B_SocketFuncConnectExitLoop,0xA0A4A21C+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0A4A394+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0A4A3B6+1
	defadr	B_SocketFuncRecvReadStatus,0xA0A4A5BA+1
	defadr	B_SocketFuncRecvExitLoop,0xA0A4A5DC+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0A4A646+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0A4A668+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0A4ADBA+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0A4ADDC+1
	defadr	B_SocketFuncListenReadStatus,0xA0A4AF34+1
	defadr	B_SocketFuncListenExitLoop,0xA0A4AF56+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0A4A800+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0A4A822+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0A4A898+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0A4A8BA+1
	defadr	B_SocketFuncSendReadStatus,0xA0A4AAB0+1
	defadr	B_SocketFuncSendExitLoop,0xA0A4AAD2+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0A4AB78+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0A4AB9A+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0A4B4A6+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0A4B4C8+1
	defadr	NU_Sleep,0xA00A275C

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
