#include "ep3.asm"
#include "ll_init.asm"


	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)



defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE
        

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA066F69A+1
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA066F438+1
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA09587DE+1

	PUBLIC	PITgetN
PITgetN:
	DCD	0xA0A3C030
	
	PUBLIC	PITret
PITret:
	DCD	0xA0956C28+1

	defadr	StoreErrInfoAndAbort,0xA04D319C
	defadr	StoreErrString,0xA04D3068

; <config>
; Autogenerated with tools/porting.js

	defadr	OldFuncInOsInit,0xA05467A4
	defadr	B_SocketFuncSocketReadStatus,0xA0A6326E+1
	defadr	B_SocketFuncSocketExitLoop,0xA0A63290+1
	defadr	B_SocketFuncBindReadStatus,0xA0A6358A+1
	defadr	B_SocketFuncBindExitLoop,0xA0A635AC+1
	defadr	B_SocketFuncConnectReadStatus,0xA0A63792+1
	defadr	B_SocketFuncConnectExitLoop,0xA0A637B4+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0A6392C+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0A6394E+1
	defadr	B_SocketFuncRecvReadStatus,0xA0A63B52+1
	defadr	B_SocketFuncRecvExitLoop,0xA0A63B74+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0A63BDE+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0A63C00+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0A64352+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0A64374+1
	defadr	B_SocketFuncListenReadStatus,0xA0A644CC+1
	defadr	B_SocketFuncListenExitLoop,0xA0A644EE+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0A63D98+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0A63DBA+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0A63E30+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0A63E52+1
	defadr	B_SocketFuncSendReadStatus,0xA0A64048+1
	defadr	B_SocketFuncSendExitLoop,0xA0A6406A+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0A64110+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0A64132+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0A64A3E+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0A64A60+1
	defadr	NU_Sleep,0xA009CD50

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
