#include "ep3.asm"
#include "ll_init.asm"


	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)



defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE
        

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02FFCEE+1
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02FFAD4+1
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA096D5C6+1
	
	PUBLIC	PITgetN
PITgetN:
	DCD	0xA0A250A8
	
	PUBLIC	PITret
PITret:
	DCD	0xA096BA66+1


	defadr	StoreErrInfoAndAbort,0xA01CE3F8
	defadr	StoreErrString,0xA01CE2C4

; <config>
; Autogenerated with tools/porting.js

	defadr	OldFuncInOsInit,0xA02305E4
	defadr	B_SkipSimErrorPopup,0xA029AED6+1
	defadr	B_SocketFuncSocketReadStatus,0xA0A46CCE+1
	defadr	B_SocketFuncSocketExitLoop,0xA0A46CF0+1
	defadr	B_SocketFuncBindReadStatus,0xA0A46FEA+1
	defadr	B_SocketFuncBindExitLoop,0xA0A4700C+1
	defadr	B_SocketFuncConnectReadStatus,0xA0A471F2+1
	defadr	B_SocketFuncConnectExitLoop,0xA0A47214+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0A4738C+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0A473AE+1
	defadr	B_SocketFuncRecvReadStatus,0xA0A475B2+1
	defadr	B_SocketFuncRecvExitLoop,0xA0A475D4+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0A4763E+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0A47660+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0A47DB2+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0A47DD4+1
	defadr	B_SocketFuncListenReadStatus,0xA0A47F2C+1
	defadr	B_SocketFuncListenExitLoop,0xA0A47F4E+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0A477F8+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0A4781A+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0A47890+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0A478B2+1
	defadr	B_SocketFuncSendReadStatus,0xA0A47AA8+1
	defadr	B_SocketFuncSendExitLoop,0xA0A47ACA+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0A47B70+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0A47B92+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0A4849E+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0A484C0+1
	defadr	NU_Sleep,0xA00A275C

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
