
#include "ep3.asm"

	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)

defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02FCC0C+1  
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02FC9D4+1 
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA0979C0E+1
	
	PUBLIC	PITgetN
PITgetN:
	DCD	0xA0A2B080
	
	PUBLIC	PITret
PITret:
	DCD	0xA09780AE+1


	defadr	StoreErrInfoAndAbort,0xA01CEDBC
	defadr	StoreErrString,0xA01CEC88

; <config>
; Autogenerated with tools/src/porting.ts

	defadr	OldFuncInOsInit,0xA0231048
	defadr	B_SkipSimErrorPopup,0xA029BD1E+1
	defadr	B_SocketFuncSocketReadStatus,0xA0A4CC4E+1
	defadr	B_SocketFuncSocketExitLoop,0xA0A4CC70+1
	defadr	B_SocketFuncBindReadStatus,0xA0A4CF6A+1
	defadr	B_SocketFuncBindExitLoop,0xA0A4CF8C+1
	defadr	B_SocketFuncConnectReadStatus,0xA0A4D172+1
	defadr	B_SocketFuncConnectExitLoop,0xA0A4D194+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0A4D30C+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0A4D32E+1
	defadr	B_SocketFuncRecvReadStatus,0xA0A4D532+1
	defadr	B_SocketFuncRecvExitLoop,0xA0A4D554+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0A4D5BE+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0A4D5E0+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0A4DD32+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0A4DD54+1
	defadr	B_SocketFuncListenReadStatus,0xA0A4DEAC+1
	defadr	B_SocketFuncListenExitLoop,0xA0A4DECE+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0A4D778+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0A4D79A+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0A4D810+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0A4D832+1
	defadr	B_SocketFuncSendReadStatus,0xA0A4DA28+1
	defadr	B_SocketFuncSendExitLoop,0xA0A4DA4A+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0A4DAF0+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0A4DB12+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0A4E41E+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0A4E440+1
	defadr	NU_Sleep,0xA00A275C

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
