
#include "ep3.asm"


	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)

defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE
        
	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02D252E+1
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02D2316+1
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA07FCF2A+1

	PUBLIC	PITgetN
PITgetN:
	DCD	0xA08A098C
	
	PUBLIC	PITret
PITret:
	DCD	0xA07FB3CA+1


	defadr	StoreErrInfoAndAbort,0xA018D9E8
	defadr	StoreErrString,0xA018D8B4

; <config>
; Autogenerated with tools/porting.js

	defadr	OldFuncInOsInit,0xA01F915C
	defadr	B_SkipSimErrorPopup,0xA0265E28+1
	defadr	B_SocketFuncSocketReadStatus,0xA0B4699E+1
	defadr	B_SocketFuncSocketExitLoop,0xA0B469C0+1
	defadr	B_SocketFuncBindReadStatus,0xA0B46CBA+1
	defadr	B_SocketFuncBindExitLoop,0xA0B46CDC+1
	defadr	B_SocketFuncConnectReadStatus,0xA0B46EC2+1
	defadr	B_SocketFuncConnectExitLoop,0xA0B46EE4+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0B4705C+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0B4707E+1
	defadr	B_SocketFuncRecvReadStatus,0xA0B47282+1
	defadr	B_SocketFuncRecvExitLoop,0xA0B472A4+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0B4730E+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0B47330+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0B47A82+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0B47AA4+1
	defadr	B_SocketFuncListenReadStatus,0xA0B47BFC+1
	defadr	B_SocketFuncListenExitLoop,0xA0B47C1E+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0B474C8+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0B474EA+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0B47560+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0B47582+1
	defadr	B_SocketFuncSendReadStatus,0xA0B47778+1
	defadr	B_SocketFuncSendExitLoop,0xA0B4779A+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0B47840+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0B47862+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0B4816E+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0B48190+1
	defadr	NU_Sleep,0xA00A1FB8

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
