
#include "ep3.asm"


	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)
        


defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE
        

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02FEDFA+1
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02FEBE4+1
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA0977222+1
	
	PUBLIC	PITgetN
PITgetN:
	DCD	0xA0A27504
	
	PUBLIC	PITret
PITret:
	DCD	0xA09756C2+1


	defadr	StoreErrInfoAndAbort,0xA01CEDBC
	defadr	StoreErrString,0xA01CEC88

; <config>
; Autogenerated with tools/porting.js

	defadr	OldFuncInOsInit,0xA0231154
	defadr	B_SkipSimErrorPopup,0xA029BD0E+1
	defadr	B_SocketFuncSocketReadStatus,0xA0A490D2+1
	defadr	B_SocketFuncSocketExitLoop,0xA0A490F4+1
	defadr	B_SocketFuncBindReadStatus,0xA0A493EE+1
	defadr	B_SocketFuncBindExitLoop,0xA0A49410+1
	defadr	B_SocketFuncConnectReadStatus,0xA0A495F6+1
	defadr	B_SocketFuncConnectExitLoop,0xA0A49618+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0A49790+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0A497B2+1
	defadr	B_SocketFuncRecvReadStatus,0xA0A499B6+1
	defadr	B_SocketFuncRecvExitLoop,0xA0A499D8+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0A49A42+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0A49A64+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0A4A1B6+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0A4A1D8+1
	defadr	B_SocketFuncListenReadStatus,0xA0A4A330+1
	defadr	B_SocketFuncListenExitLoop,0xA0A4A352+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0A49BFC+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0A49C1E+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0A49C94+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0A49CB6+1
	defadr	B_SocketFuncSendReadStatus,0xA0A49EAC+1
	defadr	B_SocketFuncSendExitLoop,0xA0A49ECE+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0A49F74+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0A49F96+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0A4A8A2+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0A4A8C4+1
	defadr	NU_Sleep,0xA00A275C

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
