
#include "ep3.asm"


	RSEG	DATA_N
	RSEG	SWILIB_FUNC1B8_1BB:CODE
	EXTERN	EXT2_AREA
	EXTERN	pngtop
	EXTERN	pLIB_TOP
	DCD	EXT2_AREA
	DCD	pngtop
	DCD	pLIB_TOP
	DCD	SFE(DATA_N)

defadr	MACRO	a,b
	PUBLIC	a
a	EQU	b
	ENDM

        RSEG	CODE:CODE
        

	PUBLIC	OldOnClose
OldOnClose:
	DCD	0xA02FCD7A+1
	
	PUBLIC	OldOnCreate
OldOnCreate:
	DCD	0xA02FCB52+1
	
	PUBLIC	OldShowMsg
OldShowMsg:
	DCD	0xA097789E+1
	
	PUBLIC	PITgetN
PITgetN:
	DCD	0xA0A27720
	
	PUBLIC	PITret
PITret:
	DCD	0xA0975D3E+1


	defadr	StoreErrInfoAndAbort,0xA01CD2E8
	defadr	StoreErrString,0xA01CD1B4

; <config>
; Autogenerated with tools/src/porting.ts

	defadr	OldFuncInOsInit,0xA022F364
	defadr	B_SkipSimErrorPopup,0xA0299D1E+1
	defadr	B_SocketFuncSocketReadStatus,0xA0A492EE+1
	defadr	B_SocketFuncSocketExitLoop,0xA0A49310+1
	defadr	B_SocketFuncBindReadStatus,0xA0A4960A+1
	defadr	B_SocketFuncBindExitLoop,0xA0A4962C+1
	defadr	B_SocketFuncConnectReadStatus,0xA0A49812+1
	defadr	B_SocketFuncConnectExitLoop,0xA0A49834+1
	defadr	B_SocketFuncShutdownReadStatus,0xA0A499AC+1
	defadr	B_SocketFuncShutdownExitLoop,0xA0A499CE+1
	defadr	B_SocketFuncRecvReadStatus,0xA0A49BD2+1
	defadr	B_SocketFuncRecvExitLoop,0xA0A49BF4+1
	defadr	B_SocketFuncRecv2ReadStatus,0xA0A49C5E+1
	defadr	B_SocketFuncRecv2ExitLoop,0xA0A49C80+1
	defadr	B_SocketFuncSendtoReadStatus,0xA0A4A3D2+1
	defadr	B_SocketFuncSendtoExitLoop,0xA0A4A3F4+1
	defadr	B_SocketFuncListenReadStatus,0xA0A4A54C+1
	defadr	B_SocketFuncListenExitLoop,0xA0A4A56E+1
	defadr	B_SocketFuncRecvfromReadStatus,0xA0A49E18+1
	defadr	B_SocketFuncRecvfromExitLoop,0xA0A49E3A+1
	defadr	B_SocketFuncRecvfrom2ReadStatus,0xA0A49EB0+1
	defadr	B_SocketFuncRecvfrom2ExitLoop,0xA0A49ED2+1
	defadr	B_SocketFuncSendReadStatus,0xA0A4A0C8+1
	defadr	B_SocketFuncSendExitLoop,0xA0A4A0EA+1
	defadr	B_SocketFuncSend2ReadStatus,0xA0A4A190+1
	defadr	B_SocketFuncSend2ExitLoop,0xA0A4A1B2+1
	defadr	B_SocketFuncGethostbynameReadStatus,0xA0A4AABE+1
	defadr	B_SocketFuncGethostbynameExitLoop,0xA0A4AAE0+1
	defadr	NU_Sleep,0xA00A275C

#include "patches/no_idle_restart.asm"
#include "patches/race_condition_in_sockets.asm"
; </config>

	END
